plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/naitiksoni/Desktop/admin-analytics-showcase/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]
  VITE_API_URL = "https://ns-command-center.onrender.com"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]